In [1]:
import numpy as np
np.random.seed(12345)

In [2]:
np.set_printoptions(precision=4)

In [4]:
np.array([1.123456789])

array([1.1235])

In [5]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [6]:
np.set_printoptions(threshold=2000)

In [7]:
np.arange(1500)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [8]:
np.set_printoptions(threshold=np.inf)

In [9]:
np.arange(1500)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [12]:
import numpy as np
data= [np.random.standard_normal() for i in range(7)]
data

[-0.20470765948471295,
 0.47894333805754824,
 -0.5194387150567381,
 -0.55573030434749,
 1.9657805725027142,
 1.3934058329729904,
 0.09290787674371767]

In [13]:
a = [1, 2, 3]
b = a

In [14]:
a==b

True

In [15]:
c=a.copy()
c

[1, 2, 3]

In [16]:
a.append(4)

In [17]:
c

[1, 2, 3]

In [18]:
c = """
This is a longer string that
spans multiple lines
"""

In [20]:
c.count("\n")

3

In [21]:
a="this is a string"

In [23]:
b=a.replace("string", "longer string")
b

'this is a longer string'

In [24]:
a=5.6
s=str(a)
print(s)

5.6


In [25]:
s="12\\34"
print(s)

12\34


In [26]:
a="This is a longer string"
b="that spans multiple lines"


In [27]:
a+b

'This is a longer stringthat spans multiple lines'

In [28]:
template = "{0:.2f} {1:s} are worth US${2:d}"

In [29]:
template.format(88.46, "Argentine Pesos", 1)

'88.46 Argentine Pesos are worth US$1'

In [30]:
amount = 10
rate = 88.46
currency = "Pesos"
result = f"{amount} {currency} is worth US${amount / rate}"

In [31]:
result

'10 Pesos is worth US$0.11304544426859599'

In [32]:
from datetime import datetime, date, time
dt = datetime(2024, 5, 21, 9, 45, 21)

In [33]:
dt

datetime.datetime(2024, 5, 21, 9, 45, 21)

In [38]:
dt.day
dt.minute
dt.date()

datetime.date(2024, 5, 21)

In [40]:
dt.time()

datetime.time(9, 45, 21)

In [41]:
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south   carolina##", "West virginia?"]

In [42]:
import re

In [50]:
def clean_strings(strings):
    result=[]
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result

In [51]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [54]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [56]:
arr =np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [57]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [58]:
float_arr.dtype

dtype('float64')

In [59]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [60]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [61]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [62]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [65]:
arr[5:8] = 12

In [66]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [67]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [68]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])

In [70]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [71]:
names[names=="Bob"]

array(['Bob', 'Bob'], dtype='<U4')

In [73]:
data[names =="Bob"]

array([[4, 7],
       [0, 0]])

In [76]:
data[names == "Bob", 0]

array([4, 0])

In [77]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [78]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [79]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [81]:
#!(names=="Bob") 문법 오류
~(names =="Bob") ~는 부정

array([False,  True,  True, False,  True,  True,  True])

In [82]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [83]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [84]:
data[~(names =="Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [85]:
cond= names =="Bob"

In [86]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [93]:
data[(names=="Bob") | (names== "Will")]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [94]:
cond = (names == "Bob") | (names == "will")
data[cond]

array([[4, 7],
       [0, 0]])

In [95]:
data<0

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [96]:
data[data<0]

array([ -5, -12,  -4])

In [97]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [98]:
data[names != 'Joe']=7

In [99]:
data

array([[  7,   7],
       [  0,   2],
       [  7,   7],
       [  7,   7],
       [  7,   7],
       [-12,  -4],
       [  3,   4]])

In [100]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [105]:
arr[[4,3,6,0],2:]

array([[4., 4.],
       [3., 3.],
       [6., 6.],
       [0., 0.]])

In [104]:
arr[-1]
arr[[-1,-5,-3]]

array([[7., 7., 7., 7.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [107]:
arr[[-1,-5,-3],1:3]

array([[7., 7.],
       [3., 3.],
       [5., 5.]])

In [108]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [116]:
arr1=arr[[1,5,7,2]]
arr1[:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [121]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [124]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [126]:
arr[:,[0,3,1,2]][[1,5,7,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [127]:
arr[[1,5,7,2],[0,3,1,2]]=0

In [128]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [129]:
arr[[1,5,7,2]]=0
arr

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  0,  0,  0],
       [24, 25, 26, 27],
       [ 0,  0,  0,  0]])

In [130]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [132]:
arr @ arr.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [133]:
arr.T @arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [135]:
arr= np.arange(10)

In [136]:
np.sqrt(arr)

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [137]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [139]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [140]:
yarr[cond]=xarr[cond]
yarr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [153]:
[(x,y,z) for x,y,z  in zip(xarr, yarr, cond)]

[(1.1, 1.1, True),
 (1.2, 2.2, False),
 (1.3, 1.3, True),
 (1.4, 1.4, True),
 (1.5, 2.5, False)]

In [143]:
res = []
for i, v in enumerate(cond):
    if v:
        res.append(xarr[i])
    else:
        res.append(yarr[i])
res

[1.1, 2.2, 1.3, 1.4, 2.5]

In [149]:
[x if z else y for x,y,z  in zip(xarr, yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [152]:
z

In [156]:
arr=np.random.standard_normal((4,4))
arr

array([[ 0.3329, -2.3594, -0.1995, -1.542 ],
       [-0.9707, -1.307 ,  0.2863,  0.378 ],
       [-0.7539,  0.3313,  1.3497,  0.0699],
       [ 0.2467, -0.0119,  1.0048,  1.3272]])

In [157]:
np.where(arr>0, 1, -1)

array([[ 1, -1, -1, -1],
       [-1, -1,  1,  1],
       [-1,  1,  1,  1],
       [ 1, -1,  1,  1]])

In [158]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
np.where(arr%3==0,3,arr)

array([[ 3,  1,  2,  3],
       [ 4,  5,  3,  7],
       [ 8,  3, 10, 11]])

In [160]:
np.mean(arr)

5.5

In [161]:
arr.mean(axis=1)

array([1.5, 5.5, 9.5])

In [162]:
arr.mean(axis=0)

array([4., 5., 6., 7.])

In [165]:
arr=np.array([0,1,2,3,4,5,6,7,])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [166]:
arr.sum()

28

In [168]:
arr = np.random.standard_normal(100)
arr

array([-1.5637e+00, -3.6749e-01,  1.0459e+00,  1.2200e+00, -2.4770e-01,
       -4.1623e-01, -1.1675e-01, -1.8448e+00,  2.0687e+00, -7.7697e-01,
        1.4402e+00, -1.1056e-01,  1.2274e+00,  1.9208e+00,  7.4643e-01,
        2.2247e+00, -6.7940e-01,  7.2737e-01, -8.6873e-01, -1.2139e+00,
       -4.7063e-01, -9.1924e-01, -8.3883e-01,  4.3516e-01, -5.5780e-01,
       -5.6745e-01, -3.7264e-01, -9.2656e-01,  1.7551e+00,  1.2098e+00,
        1.2700e+00, -9.7438e-01, -6.3471e-01, -3.9570e-01, -2.8944e-01,
       -7.3430e-01, -7.2850e-01,  8.3878e-01,  2.6689e-01,  7.2119e-01,
        9.1098e-01, -1.0209e+00, -1.4134e+00,  1.2966e+00,  2.5228e-01,
        1.1275e+00, -5.6836e-01,  3.0936e-01, -5.7739e-01, -1.1686e+00,
       -8.2502e-01, -2.6444e+00, -1.5299e-01, -7.5192e-01, -1.3261e-01,
        1.4573e+00,  6.0951e-01, -4.9378e-01,  1.2400e+00, -1.3572e-01,
        1.4300e+00, -8.4685e-01,  6.0328e-01,  1.2636e+00, -2.5549e-01,
       -4.4569e-01,  4.6837e-01, -9.6160e-01, -1.8245e+00,  6.25

In [169]:
(arr>0).sum()

43

In [170]:
(arr<=0).sum()

57

In [174]:
bools=np.array([False,False,True,False])
bools.sum()
bools.any()
bools.all()

False

In [175]:
arr2=np.array([5,-10, 7,1,0,-3])
arr2

array([  5, -10,   7,   1,   0,  -3])

In [176]:
np.sort(arr2)

array([-10,  -3,   0,   1,   5,   7])

In [177]:
arr2

array([  5, -10,   7,   1,   0,  -3])

In [178]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [179]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [181]:
set(names)
set(ints)

{1, 2, 3, 4}

In [182]:
np.save("data",arr)

In [183]:
np.save("data",arr) #arr에 저장된 데이터가 binary 형태로 data.npy에 저장됨

In [184]:
np.load("data.npy")

array([-1.5637e+00, -3.6749e-01,  1.0459e+00,  1.2200e+00, -2.4770e-01,
       -4.1623e-01, -1.1675e-01, -1.8448e+00,  2.0687e+00, -7.7697e-01,
        1.4402e+00, -1.1056e-01,  1.2274e+00,  1.9208e+00,  7.4643e-01,
        2.2247e+00, -6.7940e-01,  7.2737e-01, -8.6873e-01, -1.2139e+00,
       -4.7063e-01, -9.1924e-01, -8.3883e-01,  4.3516e-01, -5.5780e-01,
       -5.6745e-01, -3.7264e-01, -9.2656e-01,  1.7551e+00,  1.2098e+00,
        1.2700e+00, -9.7438e-01, -6.3471e-01, -3.9570e-01, -2.8944e-01,
       -7.3430e-01, -7.2850e-01,  8.3878e-01,  2.6689e-01,  7.2119e-01,
        9.1098e-01, -1.0209e+00, -1.4134e+00,  1.2966e+00,  2.5228e-01,
        1.1275e+00, -5.6836e-01,  3.0936e-01, -5.7739e-01, -1.1686e+00,
       -8.2502e-01, -2.6444e+00, -1.5299e-01, -7.5192e-01, -1.3261e-01,
        1.4573e+00,  6.0951e-01, -4.9378e-01,  1.2400e+00, -1.3572e-01,
        1.4300e+00, -8.4685e-01,  6.0328e-01,  1.2636e+00, -2.5549e-01,
       -4.4569e-01,  4.6837e-01, -9.6160e-01, -1.8245e+00,  6.25

In [185]:
brr=np.arange(10)
brr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
np.savez("data2.npz",a=arr,b=brr)

In [190]:
x=np.load("data2.npz")
x

NpzFile 'data2.npz' with keys: a, b

In [192]:
x['a']
x['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
brr.max()
brr.min()
brr.mean()

4.5

In [197]:
#시계열(series)
#표table)

In [198]:
import pandas as pd

In [200]:
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [202]:
s2=pd.Series([10,20,30,40], index=['월','화','수','목']) #행 인덱스 직접부여
s2

월    10
화    20
수    30
목    40
dtype: int64

In [203]:
pd.Series(list(range(10,15)))

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [204]:
s3=pd.Series([90,70,60,80], index=['홍길동','임꺽정','세종','인조']) #몸무게
s3

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [205]:
s3.index

Index(['홍길동', '임꺽정', '세종', '인조'], dtype='object')

In [206]:
s3.values

array([90, 70, 60, 80], dtype=int64)

In [207]:
s3.index.name="인물"

In [208]:
s3.name="몸무게"

In [209]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [210]:
s3/10

인물
홍길동    9.0
임꺽정    7.0
세종     6.0
인조     8.0
Name: 몸무게, dtype: float64

In [214]:
s3['세종']
#s3[2]
s3.iloc[2]

60

In [216]:
s3[['임꺽정','세종']]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [218]:
#s3[[1,2]]
s3.iloc[[1,2]]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [219]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [220]:
s3>70

인물
홍길동     True
임꺽정    False
세종     False
인조      True
Name: 몸무게, dtype: bool

In [221]:
s3[s3>70]

인물
홍길동    90
인조     80
Name: 몸무게, dtype: int64

In [223]:
s3[(s3 >=60) & (s3 <= 80)]

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [224]:
s3['임꺽정':'인조']

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64