In [3]:
import numpy as np

In [4]:
arr2d=np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
arr2d[:, ::-1][::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [8]:
np.flip(arr2d, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [9]:
arr2d[:,::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [10]:
arr2d[::-1, ::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [25]:
arr2d[0:2:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
arr1=np.zeros([3,3])
arr2=np.ones([3,2])
arr12=np.hstack([arr1,arr2])

In [29]:
arr3=np.arange(10,151,10).reshape(3,-1)
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [30]:
arr_v=np.vstack([arr12,arr3])

In [31]:
arr_v2=np.vstack([arr_v,arr_v])
arr_v2

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [32]:
arr1=np.zeros([3])
arr2=np.ones([2])
arr12=np.hstack([arr1,arr2])
arr12

array([0., 0., 0., 1., 1.])

In [39]:
arr12=np.tile(arr12, (3,1))

In [38]:
arr3=np.linspace(10,150,15).reshape(3,-1)
arr3

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [40]:
arr123=np.vstack([arr12,arr3])

In [41]:
np.tile(arr123,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [42]:
arr=np.arange(10,15)
arr

array([10, 11, 12, 13, 14])

In [44]:
arr.sum()

60

In [45]:
np.min(arr)

10

In [46]:
np.max(arr)

14

In [48]:
arr=np.arange(11,21).reshape(2,-1)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
np.sum(arr)
arr.sum()
np.min(arr)
np.max(arr)

20

In [54]:
arr.argmin()
arr.argmax()

9

In [55]:
arr[0].argmin()
arr[0].argmax()

4

In [56]:
arr.mean()

15.5

In [58]:
np.median(arr)
#arr.median(사용불가)

15.5

In [66]:
np.all(2>1)
np.all([2>1, 5<3])
np.all([2>1, 5<3, 3>1])
np.all([True, True, True])
np.all([True, True, True, False])

False

In [67]:
np.any([True, True, True, False])

True

In [68]:
np.all([1,2,3])
np.all([1,2,0])
np.all([1,2,0.1])

True

In [70]:
np.all(np.arange(5))
np.all(np.arange(1,4))

True

In [74]:
a=np.zeros(10, dtype=np.int32)
a==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [75]:
np.all(a==0)

True

In [76]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [83]:
np.all((a <= b) & (b <= c))

True

In [80]:
np.all((a >= b) & (b <= c))

False

In [85]:
abc=np.all([a<=b, b<=c])

np.all(b <= c) & np.all(a<=b)

True

In [87]:
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
arr.sum(axis=0)
arr.sum(axis=1)

array([10, 35])

In [92]:
arr.max(axis=0)

array([5, 6, 7, 8, 9])

In [93]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

In [94]:
a.max(axis=1)

array([ 7, 12, 15])

In [95]:
a.sort()

In [96]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [97]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

In [99]:
a.sort(axis=0)
a

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [101]:
a.sort(axis=1)
a

array([[ 1,  1,  3,  7],
       [ 2,  5,  9, 12],
       [ 4, 11, 14, 15]])

In [103]:
arr=np.array([40,20,10,30,90])
arr

array([40, 20, 10, 30, 90])

In [104]:
arr.sort()

In [105]:
arr

array([10, 20, 30, 40, 90])

In [106]:
np.mean(arr)

38.0

In [107]:
np.median(arr)

30.0

In [108]:
np.var(arr)

776.0

In [109]:
np.std(arr)

27.85677655436824

In [110]:
arr

array([10, 20, 30, 40, 90])

In [111]:
x=np.array([5,10,9,3,8])
x

array([ 5, 10,  9,  3,  8])

In [112]:
x = np.array([5, 10, 9, 3, 8])
np.sum((x - np.mean(x)) ** 2) / (len(x) - 1)

8.5

In [116]:
np.var(x)
np.var(x,ddof=1)

8.5

In [114]:
np.std(x)

2.6076809620810595

In [115]:
np.sum((x-np.mean(x))**2)/(len(x)-1)

8.5

In [117]:
x=np.arange(1,201)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [119]:
np.percentile(x,0) #최소값

1.0

In [120]:
np.percentile(x,100) #최대값

200.0

In [121]:
data=np.arange(11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
np.percentile(data, 50)

5.0