In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr.dtype

In [ ]:
type(arr[0])

In [ ]:
type(arr)

In [ ]:
arr=np.array(['APPLE', 'CHERRY', 'BANANA'])
arr.dtype

In [ ]:
arr=np.array([1,2,3], dtype=np.float16)
arr.dtype

In [ ]:
arr=np.array([1,2,3], dtype=np.float32)
arr.dtype

In [ ]:
arr=np.array([1,2,3], dtype=np.int8)
arr.dtype

In [ ]:
arr=np.array([1,2,3], dtype='i2')
arr

In [ ]:
arr=np.array([1,2,3])
arr
arr.dtype

In [ ]:
farr=arr.astype(np.float32)
farr

In [ ]:
myList=[1,2,'3']
myList

In [ ]:
type(myList)
type(myList[0])


In [ ]:
imyList=[1,2,3]
cmyList=[1,2,'3']

In [ ]:
np.array(imyList)

In [ ]:
np.array(cmyList)

In [ ]:
arr1=np.array(list(range(10,14))).reshape(2,2)
arr2=np.array(list(range(10,14))).reshape(2,2)

In [ ]:
arr1=np.array(list(range(10,14))).reshape(2,2)
arr1

In [ ]:
arr2=np.array(list(range(13,17))).reshape(2,2)
arr2

In [ ]:
arr1>arr2

In [ ]:
~(arr1==arr2) #~는 not 연산자

In [ ]:
arr1!=arr2

In [ ]:
(~(arr1==arr2)) | (~(arr1!=arr2)) # 요소간 or 연산

In [ ]:
np.arange(8)

In [ ]:
np.arange(8).reshape(2,2,2)

In [ ]:
np.array(list(range(1,25))).reshape(2,3,4)

In [ ]:
np.arange(1,25).reshape(2,3,4)

In [ ]:
data=np.arange(200)
data
data2=data.reshape(4,-1)
data2.shape

In [ ]:
data.reshape(-1,5,10)

In [ ]:
np.arange(10,34,2).reshape(3,4)

In [ ]:
arr=np.array([1,2,3,4])
idx=np.array([True,False,False,True])

In [ ]:
arr[idx]

In [ ]:
arr==1

In [ ]:
np.min(arr)
np.max(arr)

In [ ]:
arr[np.array([True, False, False, True])]

In [ ]:
arr[(arr==np.min(arr)) | (arr==np.max(arr))]

In [ ]:
arr=np.arange(11,21)

In [163]:
arr=np.array(list(range(11,21)))

In [164]:
arr %2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [165]:
arr % 2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [166]:
arr[arr %2 ==0]

array([12, 14, 16, 18, 20])

In [167]:
arr[np.array([1,3])]

array([12, 14])

In [168]:
idx=np.array([0,0,0,1,1,1,3,3,3])

In [169]:
arr[idx]

array([11, 11, 11, 12, 12, 12, 14, 14, 14])

In [ ]:
arr=np.arange(10,40).reshape(5,-1)
arr

In [ ]:
arr[:]
arr[:,:]
arr[:,[True,True,True,False,False,False]]

In [ ]:
arr[:,[True,False,True,False,True,False]]

In [ ]:
arr[:, idx]
arr[:, [0, 2, 4]]
arr[:, np.array([0, 2, 4])]
arr[:, np.arange(0, 5, 2)]

In [ ]:
arr[[2,1,3]]

In [ ]:
np.arange(2,31,2).reshape(-1,3)

In [ ]:
np.linspace(0,10,5)

In [ ]:
arr=np.arange(1,7).reshape(2,3)

In [ ]:
arr.transpose()
arr.T.T

In [ ]:
data=np.array([[1,5,0],
              [5,3,2],
              [1,2,0]])
price=np.array([[1000],
               [5000],
               [8000]])

In [ ]:
data.dot(price)

In [ ]:
data@price

In [ ]:
#1
arr=np.arange(10,15)
arr3=arr.copy()
arr3

In [ ]:
#2
arr = np.array(list(range(0,30,2)))
arr = np.arange(0,30,2)
arr

In [ ]:
#3
arr = np.arange(10,90,10).reshape(2,4)
arr

In [ ]:
#4
arr = np.arange(1,25).reshape(-1,3)
arr

In [ ]:
#5
vector = np.array(range(0, 30, 2))
vector[[12,3]]

In [ ]:
#6
matrix = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
matrix[1,3]
matrix[0,1]
matrix[2,0]
matrix[3,2]

In [ ]:
#7
arr= np.arange(-1,-6,-1)
arr

In [ ]:
#8
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x[x%3==0]
x[x%4==1]
idx = x[(x%4==1) & (x% 3==0)]
x[idx]

In [179]:
#9
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
idx1 = np.array([1])
arr2d[idx1]
idx2= np.array([True, False, False])
arr2d[idx2]
arr2d[:,[True,False,True]]

array([[1, 3],
       [4, 6],
       [7, 9]])