In [1]:
import numpy as np

In [2]:
np.random.rand()

0.8786419209105084

In [5]:
np.random.seed(20240510)

In [7]:
np.random.rand(10)

array([0.63551756, 0.67221731, 0.8370985 , 0.3230404 , 0.66728613,
       0.99852928, 0.95145872, 0.36059922, 0.68687786, 0.21542222])

In [13]:
x=np.arange(11,15)

In [9]:
np.random.shuffle(x)

In [10]:
x

array([9, 3, 4, 6, 5, 0, 7, 1, 2, 8])

In [21]:
np.random.choice(5,3,False)

array([0, 1, 4])

In [14]:
np.random.choice(x)

11

In [25]:
np.random.choice(5,4, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 2, 3, 2])

In [26]:
np.random.rand()

0.5201259014354611

In [28]:
np.random.randn()

0.03377173721967498

In [30]:
np.random.randint(5)

0

In [31]:
data=np.random.randint(5,11,size=10)

In [32]:
data

array([ 5, 10,  6, 10,  5,  6,  9,  9, 10,  5])

In [33]:
np.unique(data)

array([ 5,  6,  9, 10])

In [34]:
np.unique(data, return_counts=True)

(array([ 5,  6,  9, 10]), array([3, 2, 2, 3], dtype=int64))

In [37]:
np.bincount(data,minlength=11)

array([0, 0, 0, 0, 0, 3, 2, 0, 0, 2, 3], dtype=int64)

In [41]:
five_lotto_num=[]
for _ in range(6):
    lotto_num=[]
    while len(lotto_num)<6:
        nums=np.random.randint(1,45)
        if nums not in lotto_num:
            lotto_num.append(nums)
    five_lotto_num.append(lotto_num)
print(five_lotto_num)
    

[[40, 42, 5, 37, 41, 35], [14, 44, 25, 35, 40, 6], [16, 32, 25, 4, 41, 31], [29, 38, 15, 39, 7, 42], [9, 35, 3, 41, 1, 36], [25, 2, 18, 9, 32, 34]]


In [43]:
res=[]
for _ in range(101):
    num=np.random.randint(1,7)
    res.append(num)
print(np.mean(res))
    

3.514851485148515


In [44]:
# 동전
arr = np.array([0, 1])
print(np.random.choice(arr, 10))


[0 0 0 1 1 0 0 1 1 1]


In [45]:
# 주사위
arr = np.arange(1, 7)
arr2 = np.random.choice(arr, 100)
print(int(np.mean(arr2)))

3


In [46]:
# 로또 수 5개 출력
num = np.arange(1,46)
for i in range(5):
    print(np.random.choice(num, 6))
# 동전 10번 던져 앞뒷면 가상 실험
print(np.random.randint(2, size=10))
# 주사위 109번 던져 나온 숫자 평균
print(np.mean(np.random.randint(1,7, 100)))

[26 43  3  1  7 31]
[23 31 27 36 26 17]
[28 45 21 43  5 29]
[43 10 25 18 35 44]
[35  7  4 35 43 27]
[0 0 0 1 0 1 0 0 1 0]
3.31


In [47]:
# 로또 수 5개 출력
def generate_lotto_nums():
    return np.random.choice(np.arange(1, 46), size=6, replace=False)

for _ in range(5):
    print(generate_lotto_nums())
    
generate_lotto_nums()

# 동전을 10번 던져 앞면(숫자1)과 뒷면(숫자0)이 나오는 가상 실험을 파이썬으로 작성
np.random.choice(2, 10, p=[0.5, 0.5])

# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라
random_num = np.random.randint(1, high=7, size=100)
np.mean(random_num)

[ 7 33 16  9 43  3]
[38  1 36 41 35 25]
[ 8 31 44 22 14 43]
[32  4  2 44 43  9]
[37  3 29  1 28 13]


3.62

In [48]:
np.random.choice(2, 10, p=[0.5, 0.5])

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0])

In [49]:
#1번
a=np.arange(1,46)
res=[]
for x in range(5):
    res.append(np.random.choice(a,size=(1,6),replace=False))
res
#2번
a=np.array([0,1])
x=np.random.choice(a,size=10)
for res in x:
    if res==0:
        print("앞면")
    else:
        print("뒷면")
#3번
a=np.arange(1,7)
np.mean(np.random.choice(a,size=100))

뒷면
앞면
앞면
앞면
앞면
뒷면
앞면
앞면
뒷면
뒷면


3.51

In [ ]:
# 주사위
arr = np.arange(1, 7)
sample_arr = np.random.choice(arr, size=100)
counts = np.bincount(sample_arr)
max_count_index = np.argmax(counts) - 1
res = arr[max_count_index]
print(sample_arr)
print(counts)
print(max_count_index)
print(res)