In [2]:
import numpy as np

In [3]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr.reshape(3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arr.flatten()
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x=np.arange(3)
x

array([0, 1, 2])

In [9]:
x[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [12]:
arr=arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
arr=arr.reshape(4,3)

In [15]:
for i in arr:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [16]:
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [17]:
arr=arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [18]:
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a2=np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [21]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [22]:
a1=np.ones((2,3))
a2=np.zeros((3,3))

In [23]:
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
a1=np.ones((3,4))
a2=np.zeros((3,4))

In [25]:
np.dstack([a1,a2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [26]:
np.stack([a1,a2]).shape

(2, 3, 4)

In [29]:
r1=np.stack([a1,a2], axis=1)
r1.shape

(3, 2, 4)

In [31]:
r2=np.stack([a1,a2,], axis=2)
r2.shape

(3, 4, 2)

In [32]:
# 두 행렬 (3,4), (3,4)를 stack함수로 연결할 때 axis값에 따라 shape이 달라짐
# axis=0 => 2,3,4
# axis=1 => 3,2,4
# axis=2 => 3,4,2

In [33]:
a1=np.array([1,2,3])
a2=np.array([11,12,13])

In [35]:
np.hstack([a1,a2])

array([ 1,  2,  3, 11, 12, 13])

In [38]:
np.vstack([a1,a2])

array([[ 1,  2,  3],
       [11, 12, 13]])

In [39]:
np.r_[a1,a2]

array([ 1,  2,  3, 11, 12, 13])

In [40]:
np.c_[a1,a2]

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [43]:
arr=np.arange(6).reshape(2,3)

In [51]:
np.tile(arr,(3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [54]:
arr1=np.array([0,0,0,1,1])
np.tile(arr1,(3,1))

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]])

In [55]:
x=np.arange(3)
y=np.arange(5)

In [56]:
x,y=np.meshgrid(x,y)

In [57]:
[list(zip(x,y)) for x,y in zip(x,y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [58]:
arr1=np.array([1,2,3])
arr2=np.array([11,21,31])

In [60]:
np.concatenate([arr1,arr2])

array([ 1,  2,  3, 11, 21, 31])

In [61]:
arr1 = np.arange(6)
arr2 = np.arange(0, 51, 10)
n, m = np.meshgrid(arr1, arr2)
m + n

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [63]:
n

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [64]:
arr1 = np.arange(6)
arr2 = np.arange(0, 56, 10)

x = arr1 + arr2[:, np.newaxis]

In [65]:
arr=np.arange(6)
arr_f= [arr + i*10 for i in range(6)]
arr_f=np.array(arr_f)
print(arr_f)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [66]:
arrays = []
for i in range(6):
    arr = np.arange(0 + i * 10, 6 + i * 10)
    arrays.append(arr)

res = np.concatenate(arrays)
res.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [67]:
a=np.arange(1,5)
b=np.array([4,2,2,4])

In [68]:
np.all(a>=b)

False

In [69]:
x = np.arange(3)
y = np.array([[0],[1],[2],[3],[4]])
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [70]:
x,y=np.meshgrid(np.arange(3),np.arange(5))
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [71]:
x

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [72]:
y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [73]:
x = np.arange(3)
y=np.arange(5).reshape(5,1)
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [74]:
np.vstack([range(7)[i:i+3] for i in range(5)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])